blog/post/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('title', validators=[DataRequired()])
    content = TextAreaField('content', validators=[DataRequired()] )
    submit = SubmitField('Post')

blog/post/routes.py
from flask import render_template, redirect, flash, url_for, request, abort, Blueprint
from flask_login import login_user, logout_user, login_required, current_user
from blog import db, bcrypt
from blog.models import Users, Posts
from blog.post.forms import PostForm


posts_ = Blueprint('posts_', __name__ )

@posts_.route('/post/new', methods=['GET', 'POST'])
@login_required
def Postform():
    form = PostForm()
    if form.validate_on_submit():
        post = Posts(title= form.title.data, content= form.content.data, author= current_user )
        db.session.add(post)
        db.session.commit()
        flash('Post added successfully','info')
        return redirect(url_for('main.home'))
    return render_template("create_post.html", title= 'Posts', legend= 'New post', form= form)


@posts_.route('/post/<int:post_id>',  methods=['GET', 'POST'])
def PostID(post_id):
    post = Posts.query.get_or_404(post_id)
    return render_template('post.html', title= post.title , post= post)


@posts_.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def PostUpdate(post_id):
    post = Posts.query.get_or_404(post_id)
    if post.author != current_user:
        abort(404)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Post updated successfully!','info')
        return redirect(url_for('main.home'))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template("create_post.html", title= post.title , legend='Update post', form= form)


@posts_.route('/post/<int:post_id>/delete', methods=['POST'])
def PostDelete(post_id):
    post = Posts.query.get_or_404(post_id)
    if post.author != current_user:
        abort(404)
    db.session.delete(post)
    db.session.commit()
    flash('Post has been deleted!','info')
    return redirect(url_for('main.home'))

blog/user/routes.py
from flask import render_template, redirect, flash, url_for, request, abort, Blueprint
from blog.models import Users, Posts
from PIL import Image
import os
from blog.user.forms import RegisterForm, LoginForm, UpdateForm, RestRequestForm, RestPasswordForm
from blog.user.utils import send_reset_email
from flask_login import login_user, logout_user, login_required, current_user
from blog import db, bcrypt

end_user = Blueprint('end_user', __name__)

@end_user.route("/login", methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(username= form.username.data).first()
        if user and bcrypt.check_password_hash(user.password,form.password.data):
            login_user(user, remember= form.remember.data)
            next_page = request.args.get('next') #redirect(next_page) if next_page else
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash("Incorrect Username/Password","danger")
    return render_template("login.html", title= "Login", form= form )


@end_user.route("/register", methods=["GET","POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegisterForm()
    if form.validate_on_submit():
        pws_hash = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = Users(username= form.username.data, password= pws_hash, email= form.email.data)
        db.session.add(user)
        db.session.commit()
        flash("Succesfully registered, now you can login!", "success")
        return redirect(url_for('end_user.login'))
    return render_template("register.html", title="Register", form= form )

@end_user.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect("/")




@end_user.route("/setting", methods=['GET', 'POST'])
@login_required
def setting():
    form = UpdateForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!','success')
        return redirect(url_for('end_user.setting'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='picture/' + current_user.picture)
    return render_template('setting.html', title='setting', image_file=image_file, form=form)



@end_user.route('/user/<string:username>', methods=['GET', 'POST'])
def User_profile(username):
    page = request.args.get('page', 1 ,type= int)
    user = Users.query.filter_by(username=username).first_or_404()
    posts= Posts.query.filter_by(author = user).order_by(Posts.time.desc())\
    .paginate(page= page, per_page= 5)
    return render_template('user_profile.html', posts=posts, user= user)



@end_user.route('/rest_request', methods=['GET', 'POST'])
def RestPequest():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RestRequestForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent. Follow the instruction in your email to rest the password!','info')
        return redirect(url_for('end_user.login'))
    return render_template('rest_request.html', title= 'Rest password', form= form)


@end_user.route('/rest_password/<token>', methods=['GET', 'POST'])
def RestPassword(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = Users.verify_token(token)
    if not user:
        flash('This invaild/expired token. please try again','warning')
        return redirect(url_for('end_user.RestPequest'))
    form = RestPasswordForm()
    if form.validate_on_submit():
        hashed = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password= hashed
        db.session.commit()
        flash('Password has been Updated! Now you can log in.','success')
        return redirect(url_for('end_user.login'))
    return render_template('reset_password.html', form= form)

blog/templates/create_post.html
{% extends "layout.html" %}

{% block main %}

<div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.content.label(class= "form-control-label")}}
                    {% if form.content.errors %}
                        {{ form.content( class= "form-control form-control-lg is_invalid") }}
                        <div class= "invalid-feedback">
                            {% for error in form.content.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                                </div>
                    {% else %}
                        {{ form.content( class= "form-control from-control-lg") }}
                    {% endif %}
                </div>
                 <div class="form-group">
                     {{ form.submit(class="btn btn-outline-info") }}
                </div>
            </form>

{% endblock %}

blog/templates/error.html
{% extends "layout.html" %}
{% block main %}
<br><br>
    <div class="jumbotron">
    {% if error == 404 %}
      <h3>Page Not Found</h3>
      <!--<p class="lead">wow</p>-->
    {% else %}
      <h3>An unexpected error has occurred</h3>
      <!--<p class="lead">wow</p>-->
    {% endif %}
      <!--<hr class="my-4">-->
      <!--<p></p>-->
    <!--  <p class="lead">-->
    <!--    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>-->
    <!--  </p>-->
    </div>
{% endblock %}

blog/templates/home.html
{% extends "layout.html" %}
{% block main %}
    <div class="jumbotron">
      {% if current_user.is_authenticated %}
      <h1 class="display-4">Hello, {{ current_user.username }}!</h1>
      {% else %}
      <h1 class="display-4">Hello, world!</h1>
      {% endif %}
      <p class="lead">Welcome to MiniBlog</p>
      <hr class="my-4">
      <p>This website is for limited number of users which they can share posts individually.</p>
      <a class="btn btn-primary btn-lg" href="{{ url_for('end_user.register') }}" role="button">Sign up!</a>
    </div>
  {% for post in posts.items %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='picture/' + post.author.picture) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('end_user.User_profile', username= post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.time }}</small>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{url_for('posts_.PostUpdate', post_id= post.id)}}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>
    </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts_.PostDelete', post_id= post.id)}}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endfor %}
<br>
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
  {% if page_num %}
    {%if page_num == posts.page %}
       <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
    {% else %}
       <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
    {% endif %}
  {% else %}
  ..
  {% endif %}
{% endfor %}
{% endblock %}

blog/templates/layout.html
<!DOCTYPE html >

<html>
    <head>
        <!--meta tag-->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!--bootstrap style link CSS-->
        <link href="https://bootswatch.com/4/united/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">

        <!--bootstrap JAVAScript code-->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" ></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" ></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" ></script>

        <title>{{ title }}</title>

    </head>
    <body>
    <header class="site-header">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="{{ url_for('main.home')}}">Home</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarColor02">
            <ul class="navbar-nav ml-auto">
              {% if current_user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('posts_.Postform')}}">New post</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('end_user.setting')}}">Setting</a>
              </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('end_user.logout')}}">Logout</a>
                </li>
              {% else %}
                 <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('end_user.register')}}">Register</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('end_user.login')}}">Login</a></a>
                </li>
              {% endif %}
            </ul>
          </div>
        </nav>
      </header>
         <main role="main" class="container">
          <div class="row">
             <div class="col-md-8">
              {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                  {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                      {{ message }}
                    </div>
                  {% endfor %}
                {% endif %}
              {% endwith %}
               </div>
        </div>
      </div>
      {% block main %} {% endblock %}
    </main>
  </body>
</html>

blog/templates/login.html
{% extends "layout.html" %}

{% block main %}

<div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class= "form-control-label")}}
                    {% if form.password.errors %}
                        {{ form.password( class= "form-control form-control-lg is_invalid") }}
                        <div class= "invalid-feedback">
                            {% for error in form.password.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                                </div>
                    {% else %}
                        {{ form.password( class= "form-control from-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    <small class="text-muted">
                    {{ form.remember.label(class="form-control-label") }}
                    </small>
                     {{ form.remember(class="btn btn-outline-info") }}
                </div>
                 <div class="form-group">
                     {{ form.submit(class="btn btn-outline-info") }}
                </div>
            </form>
                <div>
                    <small class="text-muted">
                        <a class="ml-2" href="{{ url_for('end_user.RestPequest') }}">Forget password?</a>
                    </small>
                </div>
                <div>
                    <small class="ml-2 text-muted">
                        Need an account? <a class= "ml-2" href="{{ url_for('end_user.register') }}">Register now</a>
                    </small>
                </div>
</div>

{% endblock %}

blog/templates/post.html
{% extends "layout.html" %}
{% block main %}
<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='picture/' + post.author.picture) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="#">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.time }}</small>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{url_for('posts_.PostUpdate', post_id= post.id)}}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>
    </div>
  </article>

  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts_.PostDelete', post_id= post.id)}}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
 {% endblock %}

blog/templates/register.html
{% extends "layout.html" %}

{% block main %}

<div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <!--{{ form.csrf_token }}-->
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                 <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password( class= "form-control form-control-lg is_invalid") }}
                        <div class= "invalid-feedback">
                            {% for error in form.password.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                                </div>
                    {% else %}
                        {{ form.password(class="form-control from-control-lg") }}
                    {% endif %}
                </div>
                 <div class="form-group">
                    {{ form.confirm_pass.label(class="form-control-label") }}
                    {% if form.confirm_pass.errors %}
                        {{ form.confirm_pass(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_pass.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_pass(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                </fieldset>
                 <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
            </form>
            <div>
                <small class="text-muted">
                    Already have an account? <a class= "ml-2" href="{{ url_for('end_user.login') }}">Login now</a>
                </small>
            </div>
</div>

{% endblock %}

blog/templates/reset_password.html
{% extends "layout.html" %}

{% block main %}
<div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4"> Rest password</legend>
                <div class="form-group">
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password( class= "form-control form-control-lg is_invalid") }}
                        <div class= "invalid-feedback">
                            {% for error in form.password.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                                </div>
                    {% else %}
                        {{ form.password(class="form-control from-control-lg") }}
                    {% endif %}
                </div>
                 <div class="form-group">
                    {{ form.confirm_pass.label(class="form-control-label") }}
                    {% if form.confirm_pass.errors %}
                        {{ form.confirm_pass(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_pass.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_pass(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                </fieldset>
                 <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
            </form>
{% endblock %}

blog/templates/rest_request.html
{% extends "layout.html" %}

{% block main %}
<div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4"> Rest password</legend>
                <div class="form-group">
               <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                </fieldset>
                 <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
            </form>

{% endblock %}

blog/templates/setting.html
{% extends "layout.html" %}
{% block main %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock %}

blog/templates/user_profile.html
{% extends "layout.html" %}
{% block main %}
  <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
  {% for post in posts.items %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='picture/' + post.author.picture) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('end_user.User_profile', username= post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.time }}</small>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{url_for('posts_.PostUpdate', post_id= post.id)}}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>
    </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts_.PostDelete', post_id= post.id)}}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endfor %}
<br>
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
  {% if page_num %}
    {%if page_num == posts.page %}
       <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
    {% else %}
       <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
    {% endif %}
  {% else %}
  ..
  {% endif %}
{% endfor %}
{% endblock %}